version: "3.8"
services:
  ui:
    build: ./sakai-nuxt
    ports:
      - "3000:3000"
      - "24678:24678"
  db:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_PASSWORD: LiftKZ2023
      POSTGRES_DB: petition_service
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: ./backend
    ports:
      - 8080:8080
